//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCAO.DocumentManagement {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthHeader", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class AuthHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ades.ModelDocument", Namespace="http://schemas.datacontract.org/2004/07/Anadefi")]
    [System.SerializableAttribute()]
    public partial class AdesModelDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string conditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                if ((object.ReferenceEquals(this.conditionField, value) != true)) {
                    this.conditionField = value;
                    this.RaisePropertyChanged("condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file {
            get {
                return this.fileField;
            }
            set {
                if ((object.ReferenceEquals(this.fileField, value) != true)) {
                    this.fileField = value;
                    this.RaisePropertyChanged("file");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isDefault {
            get {
                return this.isDefaultField;
            }
            set {
                if ((this.isDefaultField.Equals(value) != true)) {
                    this.isDefaultField = value;
                    this.RaisePropertyChanged("isDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                if ((object.ReferenceEquals(this.labelField, value) != true)) {
                    this.labelField = value;
                    this.RaisePropertyChanged("label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                if ((object.ReferenceEquals(this.modelField, value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string section {
            get {
                return this.sectionField;
            }
            set {
                if ((object.ReferenceEquals(this.sectionField, value) != true)) {
                    this.sectionField = value;
                    this.RaisePropertyChanged("section");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight {
            get {
                return this.weightField;
            }
            set {
                if ((object.ReferenceEquals(this.weightField, value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentManagement.IDocumentManagement")]
    public interface IDocumentManagement {
        
        // CODEGEN : La génération du contrat de message depuis le message DocumentGetListRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetList", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetListResponse")]
        EFCAO.DocumentManagement.DocumentGetListResponse DocumentGetList(EFCAO.DocumentManagement.DocumentGetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetList", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetListResponse")]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetListResponse> DocumentGetListAsync(EFCAO.DocumentManagement.DocumentGetListRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message DocumentGetListForBalanceRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetListForBalance", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetListForBalanceResponse")]
        EFCAO.DocumentManagement.DocumentGetListForBalanceResponse DocumentGetListForBalance(EFCAO.DocumentManagement.DocumentGetListForBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetListForBalance", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetListForBalanceResponse")]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetListForBalanceResponse> DocumentGetListForBalanceAsync(EFCAO.DocumentManagement.DocumentGetListForBalanceRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message DocumentGetTemplateRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetTemplate", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetTemplateResponse")]
        EFCAO.DocumentManagement.DocumentGetTemplateResponse DocumentGetTemplate(EFCAO.DocumentManagement.DocumentGetTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetTemplate", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetTemplateResponse")]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetTemplateResponse> DocumentGetTemplateAsync(EFCAO.DocumentManagement.DocumentGetTemplateRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message DocumentGetParamsRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetParams", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetParamsResponse")]
        EFCAO.DocumentManagement.DocumentGetParamsResponse DocumentGetParams(EFCAO.DocumentManagement.DocumentGetParamsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetParams", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetParamsResponse")]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetParamsResponse> DocumentGetParamsAsync(EFCAO.DocumentManagement.DocumentGetParamsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message DocumentGetDataRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetData", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetDataResponse")]
        EFCAO.DocumentManagement.DocumentGetDataResponse DocumentGetData(EFCAO.DocumentManagement.DocumentGetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetData", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetDataResponse")]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetDataResponse> DocumentGetDataAsync(EFCAO.DocumentManagement.DocumentGetDataRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message DocumentGetDocumentRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetDocument", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetDocumentResponse")]
        EFCAO.DocumentManagement.DocumentGetDocumentResponse DocumentGetDocument(EFCAO.DocumentManagement.DocumentGetDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagement/DocumentGetDocument", ReplyAction="http://tempuri.org/IDocumentManagement/DocumentGetDocumentResponse")]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetDocumentResponse> DocumentGetDocumentAsync(EFCAO.DocumentManagement.DocumentGetDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string modelName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lang;
        
        public DocumentGetListRequest() {
        }
        
        public DocumentGetListRequest(EFCAO.DocumentManagement.AuthHeader AuthHeader, string modelName, string lang) {
            this.AuthHeader = AuthHeader;
            this.modelName = modelName;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetListResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EFCAO.DocumentManagement.AdesModelDocument[] DocumentGetListResult;
        
        public DocumentGetListResponse() {
        }
        
        public DocumentGetListResponse(EFCAO.DocumentManagement.AuthHeader AuthHeader, EFCAO.DocumentManagement.AdesModelDocument[] DocumentGetListResult) {
            this.AuthHeader = AuthHeader;
            this.DocumentGetListResult = DocumentGetListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetListForBalance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetListForBalanceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ulong companyKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ulong balanceKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string modelName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string lang;
        
        public DocumentGetListForBalanceRequest() {
        }
        
        public DocumentGetListForBalanceRequest(EFCAO.DocumentManagement.AuthHeader AuthHeader, ulong companyKey, ulong balanceKey, string modelName, string lang) {
            this.AuthHeader = AuthHeader;
            this.companyKey = companyKey;
            this.balanceKey = balanceKey;
            this.modelName = modelName;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetListForBalanceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetListForBalanceResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EFCAO.DocumentManagement.AdesModelDocument[] DocumentGetListForBalanceResult;
        
        public DocumentGetListForBalanceResponse() {
        }
        
        public DocumentGetListForBalanceResponse(EFCAO.DocumentManagement.AuthHeader AuthHeader, EFCAO.DocumentManagement.AdesModelDocument[] DocumentGetListForBalanceResult) {
            this.AuthHeader = AuthHeader;
            this.DocumentGetListForBalanceResult = DocumentGetListForBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetTemplate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetTemplateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string documentRef;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lang;
        
        public DocumentGetTemplateRequest() {
        }
        
        public DocumentGetTemplateRequest(EFCAO.DocumentManagement.AuthHeader AuthHeader, string documentRef, string lang) {
            this.AuthHeader = AuthHeader;
            this.documentRef = documentRef;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetTemplateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetTemplateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DocumentGetTemplateResult;
        
        public DocumentGetTemplateResponse() {
        }
        
        public DocumentGetTemplateResponse(EFCAO.DocumentManagement.AuthHeader AuthHeader, string DocumentGetTemplateResult) {
            this.AuthHeader = AuthHeader;
            this.DocumentGetTemplateResult = DocumentGetTemplateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetParams", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetParamsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string documentRef;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lang;
        
        public DocumentGetParamsRequest() {
        }
        
        public DocumentGetParamsRequest(EFCAO.DocumentManagement.AuthHeader AuthHeader, string documentRef, string lang) {
            this.AuthHeader = AuthHeader;
            this.documentRef = documentRef;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetParamsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetParamsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DocumentGetParamsResult;
        
        public DocumentGetParamsResponse() {
        }
        
        public DocumentGetParamsResponse(EFCAO.DocumentManagement.AuthHeader AuthHeader, string DocumentGetParamsResult) {
            this.AuthHeader = AuthHeader;
            this.DocumentGetParamsResult = DocumentGetParamsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ulong companyKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ulong[] balanceKeys;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] documentRefs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string units;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string currency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string lang;
        
        public DocumentGetDataRequest() {
        }
        
        public DocumentGetDataRequest(EFCAO.DocumentManagement.AuthHeader AuthHeader, ulong companyKey, ulong[] balanceKeys, string[] documentRefs, string units, string currency, string lang) {
            this.AuthHeader = AuthHeader;
            this.companyKey = companyKey;
            this.balanceKeys = balanceKeys;
            this.documentRefs = documentRefs;
            this.units = units;
            this.currency = currency;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetDataResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DocumentGetDataResult;
        
        public DocumentGetDataResponse() {
        }
        
        public DocumentGetDataResponse(EFCAO.DocumentManagement.AuthHeader AuthHeader, string DocumentGetDataResult) {
            this.AuthHeader = AuthHeader;
            this.DocumentGetDataResult = DocumentGetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetDocument", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetDocumentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ulong companyKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ulong[] balanceKeys;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] documentRefs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string units;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string currency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string lang;
        
        public DocumentGetDocumentRequest() {
        }
        
        public DocumentGetDocumentRequest(EFCAO.DocumentManagement.AuthHeader AuthHeader, ulong companyKey, ulong[] balanceKeys, string[] documentRefs, string units, string currency, string lang) {
            this.AuthHeader = AuthHeader;
            this.companyKey = companyKey;
            this.balanceKeys = balanceKeys;
            this.documentRefs = documentRefs;
            this.units = units;
            this.currency = currency;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocumentGetDocumentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DocumentGetDocumentResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.DocumentManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DocumentGetDocumentResult;
        
        public DocumentGetDocumentResponse() {
        }
        
        public DocumentGetDocumentResponse(EFCAO.DocumentManagement.AuthHeader AuthHeader, string DocumentGetDocumentResult) {
            this.AuthHeader = AuthHeader;
            this.DocumentGetDocumentResult = DocumentGetDocumentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentManagementChannel : EFCAO.DocumentManagement.IDocumentManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentManagementClient : System.ServiceModel.ClientBase<EFCAO.DocumentManagement.IDocumentManagement>, EFCAO.DocumentManagement.IDocumentManagement {
        
        public DocumentManagementClient() {
        }
        
        public DocumentManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.DocumentManagement.DocumentGetListResponse EFCAO.DocumentManagement.IDocumentManagement.DocumentGetList(EFCAO.DocumentManagement.DocumentGetListRequest request) {
            return base.Channel.DocumentGetList(request);
        }
        
        public EFCAO.DocumentManagement.AdesModelDocument[] DocumentGetList(ref EFCAO.DocumentManagement.AuthHeader AuthHeader, string modelName, string lang) {
            EFCAO.DocumentManagement.DocumentGetListRequest inValue = new EFCAO.DocumentManagement.DocumentGetListRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.modelName = modelName;
            inValue.lang = lang;
            EFCAO.DocumentManagement.DocumentGetListResponse retVal = ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetList(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.DocumentGetListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetListResponse> EFCAO.DocumentManagement.IDocumentManagement.DocumentGetListAsync(EFCAO.DocumentManagement.DocumentGetListRequest request) {
            return base.Channel.DocumentGetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetListResponse> DocumentGetListAsync(EFCAO.DocumentManagement.AuthHeader AuthHeader, string modelName, string lang) {
            EFCAO.DocumentManagement.DocumentGetListRequest inValue = new EFCAO.DocumentManagement.DocumentGetListRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.modelName = modelName;
            inValue.lang = lang;
            return ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.DocumentManagement.DocumentGetListForBalanceResponse EFCAO.DocumentManagement.IDocumentManagement.DocumentGetListForBalance(EFCAO.DocumentManagement.DocumentGetListForBalanceRequest request) {
            return base.Channel.DocumentGetListForBalance(request);
        }
        
        public EFCAO.DocumentManagement.AdesModelDocument[] DocumentGetListForBalance(ref EFCAO.DocumentManagement.AuthHeader AuthHeader, ulong companyKey, ulong balanceKey, string modelName, string lang) {
            EFCAO.DocumentManagement.DocumentGetListForBalanceRequest inValue = new EFCAO.DocumentManagement.DocumentGetListForBalanceRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.companyKey = companyKey;
            inValue.balanceKey = balanceKey;
            inValue.modelName = modelName;
            inValue.lang = lang;
            EFCAO.DocumentManagement.DocumentGetListForBalanceResponse retVal = ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetListForBalance(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.DocumentGetListForBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetListForBalanceResponse> EFCAO.DocumentManagement.IDocumentManagement.DocumentGetListForBalanceAsync(EFCAO.DocumentManagement.DocumentGetListForBalanceRequest request) {
            return base.Channel.DocumentGetListForBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetListForBalanceResponse> DocumentGetListForBalanceAsync(EFCAO.DocumentManagement.AuthHeader AuthHeader, ulong companyKey, ulong balanceKey, string modelName, string lang) {
            EFCAO.DocumentManagement.DocumentGetListForBalanceRequest inValue = new EFCAO.DocumentManagement.DocumentGetListForBalanceRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.companyKey = companyKey;
            inValue.balanceKey = balanceKey;
            inValue.modelName = modelName;
            inValue.lang = lang;
            return ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetListForBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.DocumentManagement.DocumentGetTemplateResponse EFCAO.DocumentManagement.IDocumentManagement.DocumentGetTemplate(EFCAO.DocumentManagement.DocumentGetTemplateRequest request) {
            return base.Channel.DocumentGetTemplate(request);
        }
        
        public string DocumentGetTemplate(ref EFCAO.DocumentManagement.AuthHeader AuthHeader, string documentRef, string lang) {
            EFCAO.DocumentManagement.DocumentGetTemplateRequest inValue = new EFCAO.DocumentManagement.DocumentGetTemplateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.documentRef = documentRef;
            inValue.lang = lang;
            EFCAO.DocumentManagement.DocumentGetTemplateResponse retVal = ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetTemplate(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.DocumentGetTemplateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetTemplateResponse> EFCAO.DocumentManagement.IDocumentManagement.DocumentGetTemplateAsync(EFCAO.DocumentManagement.DocumentGetTemplateRequest request) {
            return base.Channel.DocumentGetTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetTemplateResponse> DocumentGetTemplateAsync(EFCAO.DocumentManagement.AuthHeader AuthHeader, string documentRef, string lang) {
            EFCAO.DocumentManagement.DocumentGetTemplateRequest inValue = new EFCAO.DocumentManagement.DocumentGetTemplateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.documentRef = documentRef;
            inValue.lang = lang;
            return ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.DocumentManagement.DocumentGetParamsResponse EFCAO.DocumentManagement.IDocumentManagement.DocumentGetParams(EFCAO.DocumentManagement.DocumentGetParamsRequest request) {
            return base.Channel.DocumentGetParams(request);
        }
        
        public string DocumentGetParams(ref EFCAO.DocumentManagement.AuthHeader AuthHeader, string documentRef, string lang) {
            EFCAO.DocumentManagement.DocumentGetParamsRequest inValue = new EFCAO.DocumentManagement.DocumentGetParamsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.documentRef = documentRef;
            inValue.lang = lang;
            EFCAO.DocumentManagement.DocumentGetParamsResponse retVal = ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetParams(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.DocumentGetParamsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetParamsResponse> EFCAO.DocumentManagement.IDocumentManagement.DocumentGetParamsAsync(EFCAO.DocumentManagement.DocumentGetParamsRequest request) {
            return base.Channel.DocumentGetParamsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetParamsResponse> DocumentGetParamsAsync(EFCAO.DocumentManagement.AuthHeader AuthHeader, string documentRef, string lang) {
            EFCAO.DocumentManagement.DocumentGetParamsRequest inValue = new EFCAO.DocumentManagement.DocumentGetParamsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.documentRef = documentRef;
            inValue.lang = lang;
            return ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetParamsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.DocumentManagement.DocumentGetDataResponse EFCAO.DocumentManagement.IDocumentManagement.DocumentGetData(EFCAO.DocumentManagement.DocumentGetDataRequest request) {
            return base.Channel.DocumentGetData(request);
        }
        
        public string DocumentGetData(ref EFCAO.DocumentManagement.AuthHeader AuthHeader, ulong companyKey, ulong[] balanceKeys, string[] documentRefs, string units, string currency, string lang) {
            EFCAO.DocumentManagement.DocumentGetDataRequest inValue = new EFCAO.DocumentManagement.DocumentGetDataRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.companyKey = companyKey;
            inValue.balanceKeys = balanceKeys;
            inValue.documentRefs = documentRefs;
            inValue.units = units;
            inValue.currency = currency;
            inValue.lang = lang;
            EFCAO.DocumentManagement.DocumentGetDataResponse retVal = ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetData(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.DocumentGetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetDataResponse> EFCAO.DocumentManagement.IDocumentManagement.DocumentGetDataAsync(EFCAO.DocumentManagement.DocumentGetDataRequest request) {
            return base.Channel.DocumentGetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetDataResponse> DocumentGetDataAsync(EFCAO.DocumentManagement.AuthHeader AuthHeader, ulong companyKey, ulong[] balanceKeys, string[] documentRefs, string units, string currency, string lang) {
            EFCAO.DocumentManagement.DocumentGetDataRequest inValue = new EFCAO.DocumentManagement.DocumentGetDataRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.companyKey = companyKey;
            inValue.balanceKeys = balanceKeys;
            inValue.documentRefs = documentRefs;
            inValue.units = units;
            inValue.currency = currency;
            inValue.lang = lang;
            return ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.DocumentManagement.DocumentGetDocumentResponse EFCAO.DocumentManagement.IDocumentManagement.DocumentGetDocument(EFCAO.DocumentManagement.DocumentGetDocumentRequest request) {
            return base.Channel.DocumentGetDocument(request);
        }
        
        public string DocumentGetDocument(ref EFCAO.DocumentManagement.AuthHeader AuthHeader, ulong companyKey, ulong[] balanceKeys, string[] documentRefs, string units, string currency, string lang) {
            EFCAO.DocumentManagement.DocumentGetDocumentRequest inValue = new EFCAO.DocumentManagement.DocumentGetDocumentRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.companyKey = companyKey;
            inValue.balanceKeys = balanceKeys;
            inValue.documentRefs = documentRefs;
            inValue.units = units;
            inValue.currency = currency;
            inValue.lang = lang;
            EFCAO.DocumentManagement.DocumentGetDocumentResponse retVal = ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetDocument(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.DocumentGetDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetDocumentResponse> EFCAO.DocumentManagement.IDocumentManagement.DocumentGetDocumentAsync(EFCAO.DocumentManagement.DocumentGetDocumentRequest request) {
            return base.Channel.DocumentGetDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.DocumentManagement.DocumentGetDocumentResponse> DocumentGetDocumentAsync(EFCAO.DocumentManagement.AuthHeader AuthHeader, ulong companyKey, ulong[] balanceKeys, string[] documentRefs, string units, string currency, string lang) {
            EFCAO.DocumentManagement.DocumentGetDocumentRequest inValue = new EFCAO.DocumentManagement.DocumentGetDocumentRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.companyKey = companyKey;
            inValue.balanceKeys = balanceKeys;
            inValue.documentRefs = documentRefs;
            inValue.units = units;
            inValue.currency = currency;
            inValue.lang = lang;
            return ((EFCAO.DocumentManagement.IDocumentManagement)(this)).DocumentGetDocumentAsync(inValue);
        }
    }
}
