//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCAO.ParamsManagement {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthHeader", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class AuthHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ades.Reference", Namespace="http://schemas.datacontract.org/2004/07/Anadefi")]
    [System.SerializableAttribute()]
    public partial class AdesReference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                if ((object.ReferenceEquals(this.labelField, value) != true)) {
                    this.labelField = value;
                    this.RaisePropertyChanged("label");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ades.Property", Namespace="http://schemas.datacontract.org/2004/07/Anadefi")]
    [System.SerializableAttribute()]
    public partial class AdesProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ades.ModelLine", Namespace="http://schemas.datacontract.org/2004/07/Anadefi")]
    [System.SerializableAttribute()]
    public partial class AdesModelLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int attrsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string backColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int breakTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int decimalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int justifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int visibleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int attrs {
            get {
                return this.attrsField;
            }
            set {
                if ((this.attrsField.Equals(value) != true)) {
                    this.attrsField = value;
                    this.RaisePropertyChanged("attrs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string backColor {
            get {
                return this.backColorField;
            }
            set {
                if ((object.ReferenceEquals(this.backColorField, value) != true)) {
                    this.backColorField = value;
                    this.RaisePropertyChanged("backColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int breakType {
            get {
                return this.breakTypeField;
            }
            set {
                if ((this.breakTypeField.Equals(value) != true)) {
                    this.breakTypeField = value;
                    this.RaisePropertyChanged("breakType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int decimals {
            get {
                return this.decimalsField;
            }
            set {
                if ((this.decimalsField.Equals(value) != true)) {
                    this.decimalsField = value;
                    this.RaisePropertyChanged("decimals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string format {
            get {
                return this.formatField;
            }
            set {
                if ((object.ReferenceEquals(this.formatField, value) != true)) {
                    this.formatField = value;
                    this.RaisePropertyChanged("format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int justify {
            get {
                return this.justifyField;
            }
            set {
                if ((this.justifyField.Equals(value) != true)) {
                    this.justifyField = value;
                    this.RaisePropertyChanged("justify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                if ((object.ReferenceEquals(this.labelField, value) != true)) {
                    this.labelField = value;
                    this.RaisePropertyChanged("label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int line {
            get {
                return this.lineField;
            }
            set {
                if ((this.lineField.Equals(value) != true)) {
                    this.lineField = value;
                    this.RaisePropertyChanged("line");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string section {
            get {
                return this.sectionField;
            }
            set {
                if ((object.ReferenceEquals(this.sectionField, value) != true)) {
                    this.sectionField = value;
                    this.RaisePropertyChanged("section");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string textColor {
            get {
                return this.textColorField;
            }
            set {
                if ((object.ReferenceEquals(this.textColorField, value) != true)) {
                    this.textColorField = value;
                    this.RaisePropertyChanged("textColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int visible {
            get {
                return this.visibleField;
            }
            set {
                if ((this.visibleField.Equals(value) != true)) {
                    this.visibleField = value;
                    this.RaisePropertyChanged("visible");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ades.ModelDocument", Namespace="http://schemas.datacontract.org/2004/07/Anadefi")]
    [System.SerializableAttribute()]
    public partial class AdesModelDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string conditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                if ((object.ReferenceEquals(this.conditionField, value) != true)) {
                    this.conditionField = value;
                    this.RaisePropertyChanged("condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file {
            get {
                return this.fileField;
            }
            set {
                if ((object.ReferenceEquals(this.fileField, value) != true)) {
                    this.fileField = value;
                    this.RaisePropertyChanged("file");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isDefault {
            get {
                return this.isDefaultField;
            }
            set {
                if ((this.isDefaultField.Equals(value) != true)) {
                    this.isDefaultField = value;
                    this.RaisePropertyChanged("isDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                if ((object.ReferenceEquals(this.labelField, value) != true)) {
                    this.labelField = value;
                    this.RaisePropertyChanged("label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                if ((object.ReferenceEquals(this.modelField, value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string section {
            get {
                return this.sectionField;
            }
            set {
                if ((object.ReferenceEquals(this.sectionField, value) != true)) {
                    this.sectionField = value;
                    this.RaisePropertyChanged("section");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight {
            get {
                return this.weightField;
            }
            set {
                if ((object.ReferenceEquals(this.weightField, value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParamsManagement.IParamsManagement")]
    public interface IParamsManagement {
        
        // CODEGEN : La génération du contrat de message depuis le message ModelGetNamesRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetNames", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetNamesResponse")]
        EFCAO.ParamsManagement.ModelGetNamesResponse ModelGetNames(EFCAO.ParamsManagement.ModelGetNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetNames", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetNamesResponse")]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetNamesResponse> ModelGetNamesAsync(EFCAO.ParamsManagement.ModelGetNamesRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message ModelGetLinksRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetLinks", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetLinksResponse")]
        EFCAO.ParamsManagement.ModelGetLinksResponse ModelGetLinks(EFCAO.ParamsManagement.ModelGetLinksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetLinks", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetLinksResponse")]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetLinksResponse> ModelGetLinksAsync(EFCAO.ParamsManagement.ModelGetLinksRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message ModelGetMarketsRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetMarkets", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetMarketsResponse")]
        EFCAO.ParamsManagement.ModelGetMarketsResponse ModelGetMarkets(EFCAO.ParamsManagement.ModelGetMarketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetMarkets", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetMarketsResponse")]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetMarketsResponse> ModelGetMarketsAsync(EFCAO.ParamsManagement.ModelGetMarketsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message ModelGetSectionsRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetSections", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetSectionsResponse")]
        EFCAO.ParamsManagement.ModelGetSectionsResponse ModelGetSections(EFCAO.ParamsManagement.ModelGetSectionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetSections", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetSectionsResponse")]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetSectionsResponse> ModelGetSectionsAsync(EFCAO.ParamsManagement.ModelGetSectionsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message ModelGetTemplateRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetTemplate", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetTemplateResponse")]
        EFCAO.ParamsManagement.ModelGetTemplateResponse ModelGetTemplate(EFCAO.ParamsManagement.ModelGetTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetTemplate", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetTemplateResponse")]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetTemplateResponse> ModelGetTemplateAsync(EFCAO.ParamsManagement.ModelGetTemplateRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message ModelGetDocumentListRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetDocumentList", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetDocumentListResponse")]
        EFCAO.ParamsManagement.ModelGetDocumentListResponse ModelGetDocumentList(EFCAO.ParamsManagement.ModelGetDocumentListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ModelGetDocumentList", ReplyAction="http://tempuri.org/IParamsManagement/ModelGetDocumentListResponse")]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetDocumentListResponse> ModelGetDocumentListAsync(EFCAO.ParamsManagement.ModelGetDocumentListRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message ParamGetNamesRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ParamGetNames", ReplyAction="http://tempuri.org/IParamsManagement/ParamGetNamesResponse")]
        EFCAO.ParamsManagement.ParamGetNamesResponse ParamGetNames(EFCAO.ParamsManagement.ParamGetNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ParamGetNames", ReplyAction="http://tempuri.org/IParamsManagement/ParamGetNamesResponse")]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ParamGetNamesResponse> ParamGetNamesAsync(EFCAO.ParamsManagement.ParamGetNamesRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message ParamGetPolicyRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ParamGetPolicy", ReplyAction="http://tempuri.org/IParamsManagement/ParamGetPolicyResponse")]
        EFCAO.ParamsManagement.ParamGetPolicyResponse ParamGetPolicy(EFCAO.ParamsManagement.ParamGetPolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParamsManagement/ParamGetPolicy", ReplyAction="http://tempuri.org/IParamsManagement/ParamGetPolicyResponse")]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ParamGetPolicyResponse> ParamGetPolicyAsync(EFCAO.ParamsManagement.ParamGetPolicyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetNames", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetNamesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string lang;
        
        public ModelGetNamesRequest() {
        }
        
        public ModelGetNamesRequest(EFCAO.ParamsManagement.AuthHeader AuthHeader, string lang) {
            this.AuthHeader = AuthHeader;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetNamesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetNamesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EFCAO.ParamsManagement.AdesReference[] ModelGetNamesResult;
        
        public ModelGetNamesResponse() {
        }
        
        public ModelGetNamesResponse(EFCAO.ParamsManagement.AuthHeader AuthHeader, EFCAO.ParamsManagement.AdesReference[] ModelGetNamesResult) {
            this.AuthHeader = AuthHeader;
            this.ModelGetNamesResult = ModelGetNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetLinks", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetLinksRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        public ModelGetLinksRequest() {
        }
        
        public ModelGetLinksRequest(EFCAO.ParamsManagement.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetLinksResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetLinksResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EFCAO.ParamsManagement.AdesProperty[] ModelGetLinksResult;
        
        public ModelGetLinksResponse() {
        }
        
        public ModelGetLinksResponse(EFCAO.ParamsManagement.AuthHeader AuthHeader, EFCAO.ParamsManagement.AdesProperty[] ModelGetLinksResult) {
            this.AuthHeader = AuthHeader;
            this.ModelGetLinksResult = ModelGetLinksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetMarkets", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetMarketsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        public ModelGetMarketsRequest() {
        }
        
        public ModelGetMarketsRequest(EFCAO.ParamsManagement.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetMarketsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetMarketsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EFCAO.ParamsManagement.AdesProperty[] ModelGetMarketsResult;
        
        public ModelGetMarketsResponse() {
        }
        
        public ModelGetMarketsResponse(EFCAO.ParamsManagement.AuthHeader AuthHeader, EFCAO.ParamsManagement.AdesProperty[] ModelGetMarketsResult) {
            this.AuthHeader = AuthHeader;
            this.ModelGetMarketsResult = ModelGetMarketsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetSections", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetSectionsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string modelName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lang;
        
        public ModelGetSectionsRequest() {
        }
        
        public ModelGetSectionsRequest(EFCAO.ParamsManagement.AuthHeader AuthHeader, string modelName, string lang) {
            this.AuthHeader = AuthHeader;
            this.modelName = modelName;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetSectionsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetSectionsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EFCAO.ParamsManagement.AdesReference[] ModelGetSectionsResult;
        
        public ModelGetSectionsResponse() {
        }
        
        public ModelGetSectionsResponse(EFCAO.ParamsManagement.AuthHeader AuthHeader, EFCAO.ParamsManagement.AdesReference[] ModelGetSectionsResult) {
            this.AuthHeader = AuthHeader;
            this.ModelGetSectionsResult = ModelGetSectionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetTemplate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetTemplateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string modelName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lang;
        
        public ModelGetTemplateRequest() {
        }
        
        public ModelGetTemplateRequest(EFCAO.ParamsManagement.AuthHeader AuthHeader, string modelName, string lang) {
            this.AuthHeader = AuthHeader;
            this.modelName = modelName;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetTemplateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetTemplateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EFCAO.ParamsManagement.AdesModelLine[] ModelGetTemplateResult;
        
        public ModelGetTemplateResponse() {
        }
        
        public ModelGetTemplateResponse(EFCAO.ParamsManagement.AuthHeader AuthHeader, EFCAO.ParamsManagement.AdesModelLine[] ModelGetTemplateResult) {
            this.AuthHeader = AuthHeader;
            this.ModelGetTemplateResult = ModelGetTemplateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetDocumentList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetDocumentListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string modelName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lang;
        
        public ModelGetDocumentListRequest() {
        }
        
        public ModelGetDocumentListRequest(EFCAO.ParamsManagement.AuthHeader AuthHeader, string modelName, string lang) {
            this.AuthHeader = AuthHeader;
            this.modelName = modelName;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModelGetDocumentListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModelGetDocumentListResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EFCAO.ParamsManagement.AdesModelDocument[] ModelGetDocumentListResult;
        
        public ModelGetDocumentListResponse() {
        }
        
        public ModelGetDocumentListResponse(EFCAO.ParamsManagement.AuthHeader AuthHeader, EFCAO.ParamsManagement.AdesModelDocument[] ModelGetDocumentListResult) {
            this.AuthHeader = AuthHeader;
            this.ModelGetDocumentListResult = ModelGetDocumentListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParamGetNames", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParamGetNamesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string paramName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lang;
        
        public ParamGetNamesRequest() {
        }
        
        public ParamGetNamesRequest(EFCAO.ParamsManagement.AuthHeader AuthHeader, string paramName, string lang) {
            this.AuthHeader = AuthHeader;
            this.paramName = paramName;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParamGetNamesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParamGetNamesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EFCAO.ParamsManagement.AdesReference[] ParamGetNamesResult;
        
        public ParamGetNamesResponse() {
        }
        
        public ParamGetNamesResponse(EFCAO.ParamsManagement.AuthHeader AuthHeader, EFCAO.ParamsManagement.AdesReference[] ParamGetNamesResult) {
            this.AuthHeader = AuthHeader;
            this.ParamGetNamesResult = ParamGetNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParamGetPolicy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParamGetPolicyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        public ParamGetPolicyRequest() {
        }
        
        public ParamGetPolicyRequest(EFCAO.ParamsManagement.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParamGetPolicyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParamGetPolicyResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public EFCAO.ParamsManagement.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] ParamGetPolicyResult;
        
        public ParamGetPolicyResponse() {
        }
        
        public ParamGetPolicyResponse(EFCAO.ParamsManagement.AuthHeader AuthHeader, string[] ParamGetPolicyResult) {
            this.AuthHeader = AuthHeader;
            this.ParamGetPolicyResult = ParamGetPolicyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParamsManagementChannel : EFCAO.ParamsManagement.IParamsManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParamsManagementClient : System.ServiceModel.ClientBase<EFCAO.ParamsManagement.IParamsManagement>, EFCAO.ParamsManagement.IParamsManagement {
        
        public ParamsManagementClient() {
        }
        
        public ParamsManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParamsManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParamsManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParamsManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.ParamsManagement.ModelGetNamesResponse EFCAO.ParamsManagement.IParamsManagement.ModelGetNames(EFCAO.ParamsManagement.ModelGetNamesRequest request) {
            return base.Channel.ModelGetNames(request);
        }
        
        public EFCAO.ParamsManagement.AdesReference[] ModelGetNames(ref EFCAO.ParamsManagement.AuthHeader AuthHeader, string lang) {
            EFCAO.ParamsManagement.ModelGetNamesRequest inValue = new EFCAO.ParamsManagement.ModelGetNamesRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.lang = lang;
            EFCAO.ParamsManagement.ModelGetNamesResponse retVal = ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetNames(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.ModelGetNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetNamesResponse> EFCAO.ParamsManagement.IParamsManagement.ModelGetNamesAsync(EFCAO.ParamsManagement.ModelGetNamesRequest request) {
            return base.Channel.ModelGetNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetNamesResponse> ModelGetNamesAsync(EFCAO.ParamsManagement.AuthHeader AuthHeader, string lang) {
            EFCAO.ParamsManagement.ModelGetNamesRequest inValue = new EFCAO.ParamsManagement.ModelGetNamesRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.lang = lang;
            return ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.ParamsManagement.ModelGetLinksResponse EFCAO.ParamsManagement.IParamsManagement.ModelGetLinks(EFCAO.ParamsManagement.ModelGetLinksRequest request) {
            return base.Channel.ModelGetLinks(request);
        }
        
        public EFCAO.ParamsManagement.AdesProperty[] ModelGetLinks(ref EFCAO.ParamsManagement.AuthHeader AuthHeader) {
            EFCAO.ParamsManagement.ModelGetLinksRequest inValue = new EFCAO.ParamsManagement.ModelGetLinksRequest();
            inValue.AuthHeader = AuthHeader;
            EFCAO.ParamsManagement.ModelGetLinksResponse retVal = ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetLinks(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.ModelGetLinksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetLinksResponse> EFCAO.ParamsManagement.IParamsManagement.ModelGetLinksAsync(EFCAO.ParamsManagement.ModelGetLinksRequest request) {
            return base.Channel.ModelGetLinksAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetLinksResponse> ModelGetLinksAsync(EFCAO.ParamsManagement.AuthHeader AuthHeader) {
            EFCAO.ParamsManagement.ModelGetLinksRequest inValue = new EFCAO.ParamsManagement.ModelGetLinksRequest();
            inValue.AuthHeader = AuthHeader;
            return ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetLinksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.ParamsManagement.ModelGetMarketsResponse EFCAO.ParamsManagement.IParamsManagement.ModelGetMarkets(EFCAO.ParamsManagement.ModelGetMarketsRequest request) {
            return base.Channel.ModelGetMarkets(request);
        }
        
        public EFCAO.ParamsManagement.AdesProperty[] ModelGetMarkets(ref EFCAO.ParamsManagement.AuthHeader AuthHeader) {
            EFCAO.ParamsManagement.ModelGetMarketsRequest inValue = new EFCAO.ParamsManagement.ModelGetMarketsRequest();
            inValue.AuthHeader = AuthHeader;
            EFCAO.ParamsManagement.ModelGetMarketsResponse retVal = ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetMarkets(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.ModelGetMarketsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetMarketsResponse> EFCAO.ParamsManagement.IParamsManagement.ModelGetMarketsAsync(EFCAO.ParamsManagement.ModelGetMarketsRequest request) {
            return base.Channel.ModelGetMarketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetMarketsResponse> ModelGetMarketsAsync(EFCAO.ParamsManagement.AuthHeader AuthHeader) {
            EFCAO.ParamsManagement.ModelGetMarketsRequest inValue = new EFCAO.ParamsManagement.ModelGetMarketsRequest();
            inValue.AuthHeader = AuthHeader;
            return ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetMarketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.ParamsManagement.ModelGetSectionsResponse EFCAO.ParamsManagement.IParamsManagement.ModelGetSections(EFCAO.ParamsManagement.ModelGetSectionsRequest request) {
            return base.Channel.ModelGetSections(request);
        }
        
        public EFCAO.ParamsManagement.AdesReference[] ModelGetSections(ref EFCAO.ParamsManagement.AuthHeader AuthHeader, string modelName, string lang) {
            EFCAO.ParamsManagement.ModelGetSectionsRequest inValue = new EFCAO.ParamsManagement.ModelGetSectionsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.modelName = modelName;
            inValue.lang = lang;
            EFCAO.ParamsManagement.ModelGetSectionsResponse retVal = ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetSections(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.ModelGetSectionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetSectionsResponse> EFCAO.ParamsManagement.IParamsManagement.ModelGetSectionsAsync(EFCAO.ParamsManagement.ModelGetSectionsRequest request) {
            return base.Channel.ModelGetSectionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetSectionsResponse> ModelGetSectionsAsync(EFCAO.ParamsManagement.AuthHeader AuthHeader, string modelName, string lang) {
            EFCAO.ParamsManagement.ModelGetSectionsRequest inValue = new EFCAO.ParamsManagement.ModelGetSectionsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.modelName = modelName;
            inValue.lang = lang;
            return ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetSectionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.ParamsManagement.ModelGetTemplateResponse EFCAO.ParamsManagement.IParamsManagement.ModelGetTemplate(EFCAO.ParamsManagement.ModelGetTemplateRequest request) {
            return base.Channel.ModelGetTemplate(request);
        }
        
        public EFCAO.ParamsManagement.AdesModelLine[] ModelGetTemplate(ref EFCAO.ParamsManagement.AuthHeader AuthHeader, string modelName, string lang) {
            EFCAO.ParamsManagement.ModelGetTemplateRequest inValue = new EFCAO.ParamsManagement.ModelGetTemplateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.modelName = modelName;
            inValue.lang = lang;
            EFCAO.ParamsManagement.ModelGetTemplateResponse retVal = ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetTemplate(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.ModelGetTemplateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetTemplateResponse> EFCAO.ParamsManagement.IParamsManagement.ModelGetTemplateAsync(EFCAO.ParamsManagement.ModelGetTemplateRequest request) {
            return base.Channel.ModelGetTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetTemplateResponse> ModelGetTemplateAsync(EFCAO.ParamsManagement.AuthHeader AuthHeader, string modelName, string lang) {
            EFCAO.ParamsManagement.ModelGetTemplateRequest inValue = new EFCAO.ParamsManagement.ModelGetTemplateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.modelName = modelName;
            inValue.lang = lang;
            return ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.ParamsManagement.ModelGetDocumentListResponse EFCAO.ParamsManagement.IParamsManagement.ModelGetDocumentList(EFCAO.ParamsManagement.ModelGetDocumentListRequest request) {
            return base.Channel.ModelGetDocumentList(request);
        }
        
        public EFCAO.ParamsManagement.AdesModelDocument[] ModelGetDocumentList(ref EFCAO.ParamsManagement.AuthHeader AuthHeader, string modelName, string lang) {
            EFCAO.ParamsManagement.ModelGetDocumentListRequest inValue = new EFCAO.ParamsManagement.ModelGetDocumentListRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.modelName = modelName;
            inValue.lang = lang;
            EFCAO.ParamsManagement.ModelGetDocumentListResponse retVal = ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetDocumentList(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.ModelGetDocumentListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetDocumentListResponse> EFCAO.ParamsManagement.IParamsManagement.ModelGetDocumentListAsync(EFCAO.ParamsManagement.ModelGetDocumentListRequest request) {
            return base.Channel.ModelGetDocumentListAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.ParamsManagement.ModelGetDocumentListResponse> ModelGetDocumentListAsync(EFCAO.ParamsManagement.AuthHeader AuthHeader, string modelName, string lang) {
            EFCAO.ParamsManagement.ModelGetDocumentListRequest inValue = new EFCAO.ParamsManagement.ModelGetDocumentListRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.modelName = modelName;
            inValue.lang = lang;
            return ((EFCAO.ParamsManagement.IParamsManagement)(this)).ModelGetDocumentListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.ParamsManagement.ParamGetNamesResponse EFCAO.ParamsManagement.IParamsManagement.ParamGetNames(EFCAO.ParamsManagement.ParamGetNamesRequest request) {
            return base.Channel.ParamGetNames(request);
        }
        
        public EFCAO.ParamsManagement.AdesReference[] ParamGetNames(ref EFCAO.ParamsManagement.AuthHeader AuthHeader, string paramName, string lang) {
            EFCAO.ParamsManagement.ParamGetNamesRequest inValue = new EFCAO.ParamsManagement.ParamGetNamesRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.paramName = paramName;
            inValue.lang = lang;
            EFCAO.ParamsManagement.ParamGetNamesResponse retVal = ((EFCAO.ParamsManagement.IParamsManagement)(this)).ParamGetNames(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.ParamGetNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ParamGetNamesResponse> EFCAO.ParamsManagement.IParamsManagement.ParamGetNamesAsync(EFCAO.ParamsManagement.ParamGetNamesRequest request) {
            return base.Channel.ParamGetNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.ParamsManagement.ParamGetNamesResponse> ParamGetNamesAsync(EFCAO.ParamsManagement.AuthHeader AuthHeader, string paramName, string lang) {
            EFCAO.ParamsManagement.ParamGetNamesRequest inValue = new EFCAO.ParamsManagement.ParamGetNamesRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.paramName = paramName;
            inValue.lang = lang;
            return ((EFCAO.ParamsManagement.IParamsManagement)(this)).ParamGetNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EFCAO.ParamsManagement.ParamGetPolicyResponse EFCAO.ParamsManagement.IParamsManagement.ParamGetPolicy(EFCAO.ParamsManagement.ParamGetPolicyRequest request) {
            return base.Channel.ParamGetPolicy(request);
        }
        
        public string[] ParamGetPolicy(ref EFCAO.ParamsManagement.AuthHeader AuthHeader) {
            EFCAO.ParamsManagement.ParamGetPolicyRequest inValue = new EFCAO.ParamsManagement.ParamGetPolicyRequest();
            inValue.AuthHeader = AuthHeader;
            EFCAO.ParamsManagement.ParamGetPolicyResponse retVal = ((EFCAO.ParamsManagement.IParamsManagement)(this)).ParamGetPolicy(inValue);
            AuthHeader = retVal.AuthHeader;
            return retVal.ParamGetPolicyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EFCAO.ParamsManagement.ParamGetPolicyResponse> EFCAO.ParamsManagement.IParamsManagement.ParamGetPolicyAsync(EFCAO.ParamsManagement.ParamGetPolicyRequest request) {
            return base.Channel.ParamGetPolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task<EFCAO.ParamsManagement.ParamGetPolicyResponse> ParamGetPolicyAsync(EFCAO.ParamsManagement.AuthHeader AuthHeader) {
            EFCAO.ParamsManagement.ParamGetPolicyRequest inValue = new EFCAO.ParamsManagement.ParamGetPolicyRequest();
            inValue.AuthHeader = AuthHeader;
            return ((EFCAO.ParamsManagement.IParamsManagement)(this)).ParamGetPolicyAsync(inValue);
        }
    }
}
